events{}


http {

    server {
        
        listen 80;

        #serving index file with form
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }   

        #proxing user request with fetch to api point.
        location /send-transaction {
            proxy_pass http://app:8000/send-transaction;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}